export default {
  indent_size: `5`,
  indent_char: ' ',
  indent_with_tabs: false,
  editorconfig: false,
  eol: '\n',
  end_with_newline: false,
  indent_level: 0,
  preserve_newlines: true,
  max_preserve_newlines: 25,
  space_in_paren: false,
  space_in_empty_paren: false,
  jslint_happy: true,
  space_after_anon_function: false,
  space_after_named_function: false,
  brace_style: 'none',
  unindent_chained_methods: false,
  break_chained_methods: false,
  keep_array_indentation: false,
  unescape_strings: false,
  wrap_line_length: 0,
  e4x: false,
  comma_first: false,
  operator_position: 'preserve-newline',
  indent_empty_lines: false,
  templating: ['auto'],
  'space-in-paren': false,
};
